<a href="https://colab.research.google.com/github/utamiamel/ProjectUASEDA/blob/main/UAS_EDA_UIN_Kelompok_1_Sem_Ganjil_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade git+https://github.com/kevctae/twint.git
!pip install nest_asyncio
!pip install unidecode
!pip install Sastrawi
import nltk
nltk.download('punkt')

In [2]:
import warnings; warnings.simplefilter('ignore')
import itertools, re, nltk
import time, numpy as np, matplotlib.pyplot as plt, pandas as pd, seaborn as sns 
from matplotlib.colors import ListedColormap
from textblob import TextBlob
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from unidecode import unidecode
from nltk.tag import CRFTagger
from html import unescape
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from tqdm import tqdm

factory = StopWordRemoverFactory()
stemmer = StemmerFactory().create_stemmer()
sns.set(style="ticks", color_codes=True)
random_state = 170

import twint
import nest_asyncio
import pandas as pd

from google.colab import files

Sastrawi_StopWords_id = factory.get_stop_words()

print(Sastrawi_StopWords_id)
print(len(Sastrawi_StopWords_id))

Sastrawi_StopWords_id = set(Sastrawi_StopWords_id)

['yang', 'untuk', 'pada', 'ke', 'para', 'namun', 'menurut', 'antara', 'dia', 'dua', 'ia', 'seperti', 'jika', 'jika', 'sehingga', 'kembali', 'dan', 'tidak', 'ini', 'karena', 'kepada', 'oleh', 'saat', 'harus', 'sementara', 'setelah', 'belum', 'kami', 'sekitar', 'bagi', 'serta', 'di', 'dari', 'telah', 'sebagai', 'masih', 'hal', 'ketika', 'adalah', 'itu', 'dalam', 'bisa', 'bahwa', 'atau', 'hanya', 'kita', 'dengan', 'akan', 'juga', 'ada', 'mereka', 'sudah', 'saya', 'terhadap', 'secara', 'agar', 'lain', 'anda', 'begitu', 'mengapa', 'kenapa', 'yaitu', 'yakni', 'daripada', 'itulah', 'lagi', 'maka', 'tentang', 'demi', 'dimana', 'kemana', 'pula', 'sambil', 'sebelum', 'sesudah', 'supaya', 'guna', 'kah', 'pun', 'sampai', 'sedangkan', 'selagi', 'sementara', 'tetapi', 'apakah', 'kecuali', 'sebab', 'selain', 'seolah', 'seraya', 'seterusnya', 'tanpa', 'agak', 'boleh', 'dapat', 'dsb', 'dst', 'dll', 'dahulu', 'dulunya', 'anu', 'demikian', 'tapi', 'ingin', 'juga', 'nggak', 'mari', 'nanti', 'melainkan', 'oh', 'ok', 'seharusnya', 'sebetulnya', 'setiap', 'setidaknya', 'sesuatu', 'pasti', 'saja', 'toh', 'ya', 'walau', 'tolong', 'tentu', 'amat', 'apalagi', 'bagaimanapun']
126

In [3]:
#get data
nest_asyncio.apply()
config = twint.Config()
config.Hide_output = True
config.Pandas = True
config.Retweets = True
config.Profile_full = True

config.Search = "piala dunia 2022 qatar"
config.Limit = 10000

twint.run.Search(config)
data = twint.storage.panda.Tweets_df
del twint, config, nest_asyncio
print(data.shape)

data.head()

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
(3651, 38)

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1607973776888856581,1607973776888856581,1.672206e+12,2022-12-28 05:36:37,+0000,,Besaran gaji piala dunia 2022 Qatar https://t...,in,[],[],...,,,,,,[],,,,
1,1607970378282070017,1607970378282070017,1.672205e+12,2022-12-28 05:23:07,+0000,,"90 WNI Volunteer di Piala Dunia Qatar 2022, Ja...",in,[],[],...,,,,,,[],,,,
2,1607963545509195777,1607963545509195777,1.672203e+12,2022-12-28 04:55:58,+0000,,"Congratulations buat argentina, sdh berhasil m...",in,[],[],...,,,,,,[],,,,
3,1607957220754620416,1607957220754620416,1.672202e+12,2022-12-28 04:30:50,+0000,,Piala Dunia Qatar 2022 Dinobatkan Jadi Piala D...,in,[],[],...,,,,,,[],,,,
4,1607956616367964160,1607956616367964160,1.672202e+12,2022-12-28 04:28:26,+0000,,Ayam Burger King ini ibarat Qatar di Piala Dun...,in,[],[],...,,,,,,[],,,,

In [ ]:
#get data
nest_asyncio.apply()
config = twint.Config()
config.Hide_output = True
config.Pandas = True
config.Retweets = True
config.Profile_full = True

config.Search = "final piala dunia"
config.Limit = 10000

twint.run.Search(config)
data = twint.storage.panda.Tweets_df
del twint, config, nest_asyncio
print(data.shape)

data.head()

[!] No more data! Scraping will stop now.
found 0 deleted tweets in this search.
(3651, 38)

,id,conversation_id,created_at,date,timezone,place,tweet,language,hashtags,cashtags,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1607973776888856581,1607973776888856581,1.672206e+12,2022-12-28 05:36:37,+0000,,Besaran gaji piala dunia 2022 Qatar https://t...,in,[],[],...,,,,,,[],,,,
1,1607970378282070017,1607970378282070017,1.672205e+12,2022-12-28 05:23:07,+0000,,"90 WNI Volunteer di Piala Dunia Qatar 2022, Ja...",in,[],[],...,,,,,,[],,,,
2,1607963545509195777,1607963545509195777,1.672203e+12,2022-12-28 04:55:58,+0000,,"Congratulations buat argentina, sdh berhasil m...",in,[],[],...,,,,,,[],,,,
3,1607957220754620416,1607957220754620416,1.672202e+12,2022-12-28 04:30:50,+0000,,Piala Dunia Qatar 2022 Dinobatkan Jadi Piala D...,in,[],[],...,,,,,,[],,,,
4,1607956616367964160,1607956616367964160,1.672202e+12,2022-12-28 04:28:26,+0000,,Ayam Burger King ini ibarat Qatar di Piala Dun...,in,[],[],...,,,,,,[],,,,

In [ ]:
data

In [4]:
df = data[['tweet']]
def cleanText(txt):
    docx = unidecode(unescape(txt.lower().strip()))
    urlPattern = re.compile(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
    docx = re.sub(urlPattern,' ', docx) # Remove links
    docx = re.sub(r'[^\w]', ' ', docx) # Remove Symbol, keep "_" ... recommended
    Tokens = TextBlob(docx).words # Tokenisasi 
    docx = ' '.join([t for t in Tokens if str(t) not in Sastrawi_StopWords_id and len(t)>2]) # Stopwords filtering
    docx = stemmer.stem(docx)
    return docx # Silahkan latihan tambahkan penanganan Slang/Singkatan
df['clean_tweet'] = '' # inititate kolom kosong
for idx, post in tqdm(df.iterrows()):
    df.at[idx, 'clean_tweet'] = cleanText(post.tweet)
    
df

3651it [11:47,  5.16it/s]

,tweet,clean_tweet
0,Besaran gaji piala dunia 2022 Qatar https://t...,besar gaji piala dunia 2022 qatar
1,"90 WNI Volunteer di Piala Dunia Qatar 2022, Ja...",wni volunteer piala dunia qatar 2022 jadi duta...
2,"Congratulations buat argentina, sdh berhasil m...",congratulations buat argentina sdh hasil mnjdi...
3,Piala Dunia Qatar 2022 Dinobatkan Jadi Piala D...,piala dunia qatar 2022 nobat jadi piala dunia ...
4,Ayam Burger King ini ibarat Qatar di Piala Dun...,ayam burger king ibarat qatar piala dunia 2022
...,...,...
3646,TEBAK SCORE BERHADIAH PIALA DUNIA 2022 QATAR 🌟...,tebak score hadiah piala dunia 2022 qatar hadi...
3647,FIFA Siapkan Bonus Jutaan Dolar bagi Klub yang...,fifa siap bonus juta dolar klub main ikut tamp...
3648,... serta Pay TV Parabola berbayar di @nexpara...,pay parabola bayar nexparabola tv lalu channel...
3649,Piala Dunia FIFA 2022 di Qatar akan segera ber...,piala dunia fifa 2022 qatar segera akhir weeke...
3650,semangat argentina semoga diberi kelancaran me...,semangat argentina moga beri lancar raih juara...

In [9]:
df = df[["clean_tweet"]]
df

                                            clean_tweet
0                     besar gaji piala dunia 2022 qatar
1     wni volunteer piala dunia qatar 2022 jadi duta...
2     congratulations buat argentina sdh hasil mnjdi...
3     piala dunia qatar 2022 nobat jadi piala dunia ...
4        ayam burger king ibarat qatar piala dunia 2022
...                                                 ...
3646  tebak score hadiah piala dunia 2022 qatar hadi...
3647  fifa siap bonus juta dolar klub main ikut tamp...
3648  pay parabola bayar nexparabola tv lalu channel...
3649  piala dunia fifa 2022 qatar segera akhir weeke...
3650  semangat argentina moga beri lancar raih juara...

[3651 rows x 1 columns]

In [8]:
df.to_csv("data_tweet.csv",index=False, encoding='utf8', header=False)
files.download('data_tweet.csv')

In [ ]:
#df = df[['clean_tweet']]

In [ ]:
#df.to_csv("data.csv",index=False, encoding='utf8', header=False)
#files.download('data.csv')

In [ ]:
df

,tweet,clean_tweet
0,Mengenang gegap gempita piala dunia 2022 Qatar...,kenang gegap gempita piala dunia 2022 qatar bt...
1,Argentina kembali bikin sejarah dalam sepak bo...,argentina bikin sejarah sepak bola menang pial...
2,#youtube Stadion Piala dunia Qatar 2022 yang d...,youtube stadion piala dunia qatar 2022 buat ba...
3,#youtube 8 stadion mewah dan canggih Piala Dun...,youtube stadion mewah canggih piala dunia qata...
4,8 stadion mewah dan canggih Piala Dunia Qatar ...,stadion mewah canggih piala dunia qatar 2022 n...
...,...,...
3609,TEBAK SCORE BERHADIAH PIALA DUNIA 2022 QATAR 🌟...,tebak score hadiah piala dunia 2022 qatar hadi...
3610,FIFA Siapkan Bonus Jutaan Dolar bagi Klub yang...,fifa siap bonus juta dolar klub main ikut tamp...
3611,... serta Pay TV Parabola berbayar di @nexpara...,pay parabola bayar nexparabola tv lalu channel...
3612,Piala Dunia FIFA 2022 di Qatar akan segera ber...,piala dunia fifa 2022 qatar segera akhir weeke...
3613,semangat argentina semoga diberi kelancaran me...,semangat argentina moga beri lancar raih juara...

In [ ]:
# Importing Some Python Modules
import warnings; warnings.simplefilter('ignore')
import scipy, itertools, pandas as pd, matplotlib.pyplot as plt, seaborn as sns, numpy as np
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler

plt.style.use('bmh'); sns.set()

In [ ]:
df.describe().transpose()

,count,unique,top,freq
tweet,3614,3403,#youtube Stadion Piala dunia Qatar 2022 yang d...,17
clean_tweet,3614,3000,news berita fakta indonesia viral beritaterkin...,52

In [ ]:
df.describe()

,tweet,clean_tweet
count,3614,3614
unique,3403,3000
top,#youtube Stadion Piala dunia Qatar 2022 yang d...,news berita fakta indonesia viral beritaterkin...
freq,17,52